### ISSUE TITLE
must these code run in jupyter ?

### ISSUE THREAD

**Issue by ckl8964** [llSourcell/How-to-Predict-Stock-Prices-Easily-Demo#7]
I just copy the code from stockdemo.ipynb into a .py file. Then, put all other 3 files into a folder and run under my ubuntu. Everything runs fine except the output prediction plot looks quite different from yours.

Must it be run under jupyter ?

**Comment by Steviey** [comment]
Hey @ckl8964, sorry for my interference. I'm totally new to Python. Can you explain how to copy the code from stockdemo.jpnb into a .py file? If I open it with a text-editor it's seem to be only bytecode.
Thank you.

**Comment by ckl8964** [comment]
Hi, Steviey, 

Double click the stockdemo.ipynb from the code tab here. It is not a jpnb file. You can see the python source code of the stockdemo.ipynb and the prediction result graph.
