### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by zhivko** [llSourcell/How-to-Predict-Stock-Prices-Easily-Demo#8]
Testing this on python3 and jupyter notebook, I get:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-c37cab15883e> in <module>()
      1 #Step 4 - Plot the predictions!
----> 2 predictions = lstm.predict_sequences_multiple(model, X_test, 50, 50)
      3 lstm.plot_results_multiple(predictions, y_test, 50)

~\git\How-to-Predict-Stock-Prices-Easily-Demo\lstm.py in predict_sequences_multiple(model, data, window_size, prediction_len)
     99     #Predict sequence of 50 steps before shifting prediction run forward by 50 steps
    100     prediction_seqs = []
--> 101     for i in xrange(len(data)/prediction_len):
    102         curr_frame = data[i*prediction_len]
    103         predicted = []

NameError: name 'xrange' is not defined

**Comment by zhivko** [comment]
Replacing xrange with range for python3 I get this:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-c37cab15883e> in <module>()
      1 #Step 4 - Plot the predictions!
----> 2 predictions = lstm.predict_sequences_multiple(model, X_test, 50, 50)
      3 lstm.plot_results_multiple(predictions, y_test, 50)

~\git\How-to-Predict-Stock-Prices-Easily-Demo\lstm.py in predict_sequences_multiple(model, data, window_size, prediction_len)
     99     #Predict sequence of 50 steps before shifting prediction run forward by 50 steps
    100     prediction_seqs = []
--> 101     for i in range(len(data)/prediction_len):
    102         curr_frame = data[i*prediction_len]
    103         predicted = []

TypeError: 'float' object cannot be interpreted as an integer

**Comment by zhivko** [comment]
OK fixed it with int() function and range for usage in python3.

**Comment by fleeaway** [comment]
sorry, i don't understand,is **for i in range(int(len(data)/prediction_len)）**？？
